In [ ]:
!cd ../

In [ ]:
import pandas as pd

In [ ]:
train_df = pd.read_csv("./data/raw/ghc/ghc_train.tsv", sep="\t", header=0)
test_df = pd.read_csv("./data/raw/ghc/ghc_test.tsv", sep="\t", header=0)

In [12]:
print(f"{train_df.shape=}")
print(f"{test_df.shape=}")

train_df.shape=(22036, 4)
test_df.shape=(5510, 4)

In [13]:
train_df.head()

                                                text  hd  cv  vo
0  He most likely converted to islam due to his n...   0   0   0
1  So Ford lied about being a psychologist. Recor...   0   0   0
2     Jobs. Education. Ending abuse of Nation. CA43.   0   0   0
3  I share a lot of your values, & like many who ...   0   0   0
4  I am so ready to get back to blogging! www.ben...   0   0   0

In [14]:
test_df.head()

                                                text  hd  cv  vo
0  https://www.youtube.com/watch?v=kACWpKAKtak A ...   0   0   0
1  Very nice! I tend to get tired of the constant...   0   0   0
2        Watch today. https://circumcisionmovie.com/   0   0   0
3  " Thinking Venues " First Color Layer blocking...   0   0   0
4  What about death penalty for perpetrators  and...   0   0   0