In [3]:
!cd /app

In [4]:
import pandas as pd

In [12]:
train_df = pd.read_csv("./data/raw/jigsaw-toxic-comment/train.csv")
test_df = pd.read_csv("./data/raw/jigsaw-toxic-comment/test.csv")
test_labels_df = pd.read_csv("./data/raw/jigsaw-toxic-comment/test_labels.csv")

In [13]:
print(f"{train_df.shape=}")
print(f"{test_df.shape=}")
print(f"{test_labels_df.shape=}")

train_df.shape=(159571, 8)
test_df.shape=(153164, 2)
test_labels_df.shape=(153164, 7)

In [14]:
train_df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0

In [15]:
test_df.head()

                 id                                       comment_text
0  00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1  0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2  00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3  00017563c3f7919a  :If you have a look back at the source, the in...
4  00017695ad8997eb          I don't anonymously edit articles at all.

In [16]:
test_labels_df.head()

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,00001cee341fdb12,-1,-1,-1,-1,-1,-1
1,0000247867823ef7,-1,-1,-1,-1,-1,-1
2,00013b17ad220c46,-1,-1,-1,-1,-1,-1
3,00017563c3f7919a,-1,-1,-1,-1,-1,-1
4,00017695ad8997eb,-1,-1,-1,-1,-1,-1

In [17]:
test_labels_df["toxic"].unique()

array([-1,  0,  1])

In [18]:
test_labels_df[test_labels_df["toxic"] != -1].shape

(63978, 7)

In [22]:
test_labels_df[
    (test_labels_df["toxic"] != -1) &
    (test_labels_df["severe_toxic"] != -1) &
    (test_labels_df["obscene"] != -1) &
    (test_labels_df["threat"] != -1) &
    (test_labels_df["insult"] != -1) &
    (test_labels_df["identity_hate"] != -1)
].shape

(63978, 7)